In [3]:
import pandas as pd 
from ydata_profiling import ProfileReport

df = pd.read_csv(r"C:\Users\varun\projects ml and data preprocessing\project 2\Thyroid_Diff.csv")

profile = ProfileReport(df, title="thyroid cancer dataset", explorative=True)

profile.to_file("thyroid_dataset_report.html")

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

  0%|                                                                                           | 0/17 [00:00<?, ?it/s]
100%|█████████████████████████████████████████████████████████████████████████████████| 17/17 [00:00<00:00, 110.15it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

In [7]:
df.head(10)

,Age,Gender,Smoking,Hx Smoking,Hx Radiothreapy,Thyroid Function,Physical Examination,Adenopathy,Pathology,Focality,Risk,T,N,M,Stage,Response,Recurred
0,27,F,No,No,No,Euthyroid,Single nodular goiter-left,No,Micropapillary,Uni-Focal,Low,T1a,N0,M0,I,Indeterminate,No
1,34,F,No,Yes,No,Euthyroid,Multinodular goiter,No,Micropapillary,Uni-Focal,Low,T1a,N0,M0,I,Excellent,No
2,30,F,No,No,No,Euthyroid,Single nodular goiter-right,No,Micropapillary,Uni-Focal,Low,T1a,N0,M0,I,Excellent,No
3,62,F,No,No,No,Euthyroid,Single nodular goiter-right,No,Micropapillary,Uni-Focal,Low,T1a,N0,M0,I,Excellent,No
4,62,F,No,No,No,Euthyroid,Multinodular goiter,No,Micropapillary,Multi-Focal,Low,T1a,N0,M0,I,Excellent,No
5,52,M,Yes,No,No,Euthyroid,Multinodular goiter,No,Micropapillary,Multi-Focal,Low,T1a,N0,M0,I,Indeterminate,No
6,41,F,No,Yes,No,Clinical Hyperthyroidism,Single nodular goiter-right,No,Micropapillary,Uni-Focal,Low,T1a,N0,M0,I,Excellent,No
7,46,F,No,No,No,Euthyroid,Single nodular goiter-right,No,Micropapillary,Uni-Focal,Low,T1a,N0,M0,I,Excellent,No
8,51,F,No,No,No,Euthyroid,Single nodular goiter-right,No,Micropapillary,Uni-Focal,Low,T1a,N0,M0,I,Excellent,No
9,40,F,No,No,No,Euthyroid,Single nodular goiter-right,No,Micropapillary,Uni-Focal,Low,T1a,N0,M0,I,Excellent,No

In [20]:
df['Thyroid Function'].unique()

array(['Euthyroid', 'Clinical Hyperthyroidism', 'Clinical Hypothyroidism',
       'Subclinical Hyperthyroidism', 'Subclinical Hypothyroidism'],
      dtype=object)

In [21]:
df['Physical Examination'].unique()

array(['Single nodular goiter-left', 'Multinodular goiter',
       'Single nodular goiter-right', 'Normal', 'Diffuse goiter'],
      dtype=object)

In [22]:
from sklearn.preprocessing import OrdinalEncoder

In [23]:
for col in df.select_dtypes(include='object').columns:
    print(col, df[col].unique())

Gender ['F' 'M']
Smoking ['No' 'Yes']
Hx Smoking ['No' 'Yes']
Hx Radiothreapy ['No' 'Yes']
Thyroid Function ['Euthyroid' 'Clinical Hyperthyroidism' 'Clinical Hypothyroidism'
 'Subclinical Hyperthyroidism' 'Subclinical Hypothyroidism']
Physical Examination ['Single nodular goiter-left' 'Multinodular goiter'
 'Single nodular goiter-right' 'Normal' 'Diffuse goiter']
Adenopathy ['No' 'Right' 'Extensive' 'Left' 'Bilateral' 'Posterior']
Pathology ['Micropapillary' 'Papillary' 'Follicular' 'Hurthel cell']
Focality ['Uni-Focal' 'Multi-Focal']
Recurred ['No' 'Yes']

In [29]:
df = pd.read_csv(r"C:\Users\varun\projects ml and data preprocessing\project 2\Thyroid_Diff.csv")

from sklearn.preprocessing import OrdinalEncoder

ordinal_columns = ['Risk','Stage','T','N','M','Response']

ordinal_categories = [
['Low','Intermediate','High'],
['I','II','III','IVA','IVB'],
['T1a','T1b','T2','T3a','T3b','T4a','T4b'],
['N0','N1a','N1b'],
['M0','M1'],
['Excellent','Indeterminate','Biochemical Incomplete','Structural Incomplete']
]

encoder = OrdinalEncoder(categories=ordinal_categories)

df[ordinal_columns] = encoder.fit_transform(df[ordinal_columns])

In [30]:
df['Recurred'] = df['Recurred'].map({'No':0,'Yes':1})

In [31]:
df = pd.get_dummies(df, columns=[
'Gender','Smoking','Hx Smoking','Hx Radiothreapy',
'Thyroid Function','Physical Examination',
'Adenopathy','Pathology','Focality'
])

In [32]:
print(df.select_dtypes(include='object').columns)

Index([], dtype='object')

In [33]:
df.head(10)

,Age,Risk,T,N,M,Stage,Response,Recurred,Gender_F,Gender_M,...,Adenopathy_Left,Adenopathy_No,Adenopathy_Posterior,Adenopathy_Right,Pathology_Follicular,Pathology_Hurthel cell,Pathology_Micropapillary,Pathology_Papillary,Focality_Multi-Focal,Focality_Uni-Focal
0,27,0.0,0.0,0.0,0.0,0.0,1.0,0,True,False,...,False,True,False,False,False,False,True,False,False,True
1,34,0.0,0.0,0.0,0.0,0.0,0.0,0,True,False,...,False,True,False,False,False,False,True,False,False,True
2,30,0.0,0.0,0.0,0.0,0.0,0.0,0,True,False,...,False,True,False,False,False,False,True,False,False,True
3,62,0.0,0.0,0.0,0.0,0.0,0.0,0,True,False,...,False,True,False,False,False,False,True,False,False,True
4,62,0.0,0.0,0.0,0.0,0.0,0.0,0,True,False,...,False,True,False,False,False,False,True,False,True,False
5,52,0.0,0.0,0.0,0.0,0.0,1.0,0,False,True,...,False,True,False,False,False,False,True,False,True,False
6,41,0.0,0.0,0.0,0.0,0.0,0.0,0,True,False,...,False,True,False,False,False,False,True,False,False,True
7,46,0.0,0.0,0.0,0.0,0.0,0.0,0,True,False,...,False,True,False,False,False,False,True,False,False,True
8,51,0.0,0.0,0.0,0.0,0.0,0.0,0,True,False,...,False,True,False,False,False,False,True,False,False,True
9,40,0.0,0.0,0.0,0.0,0.0,0.0,0,True,False,...,False,True,False,False,False,False,True,False,False,True

In [34]:
bool_cols = df.select_dtypes(include='bool').columns
df[bool_cols] = df[bool_cols].astype(int)

In [36]:
df.head(10)

,Age,Risk,T,N,M,Stage,Response,Recurred,Gender_F,Gender_M,...,Adenopathy_Left,Adenopathy_No,Adenopathy_Posterior,Adenopathy_Right,Pathology_Follicular,Pathology_Hurthel cell,Pathology_Micropapillary,Pathology_Papillary,Focality_Multi-Focal,Focality_Uni-Focal
0,27,0.0,0.0,0.0,0.0,0.0,1.0,0,1,0,...,0,1,0,0,0,0,1,0,0,1
1,34,0.0,0.0,0.0,0.0,0.0,0.0,0,1,0,...,0,1,0,0,0,0,1,0,0,1
2,30,0.0,0.0,0.0,0.0,0.0,0.0,0,1,0,...,0,1,0,0,0,0,1,0,0,1
3,62,0.0,0.0,0.0,0.0,0.0,0.0,0,1,0,...,0,1,0,0,0,0,1,0,0,1
4,62,0.0,0.0,0.0,0.0,0.0,0.0,0,1,0,...,0,1,0,0,0,0,1,0,1,0
5,52,0.0,0.0,0.0,0.0,0.0,1.0,0,0,1,...,0,1,0,0,0,0,1,0,1,0
6,41,0.0,0.0,0.0,0.0,0.0,0.0,0,1,0,...,0,1,0,0,0,0,1,0,0,1
7,46,0.0,0.0,0.0,0.0,0.0,0.0,0,1,0,...,0,1,0,0,0,0,1,0,0,1
8,51,0.0,0.0,0.0,0.0,0.0,0.0,0,1,0,...,0,1,0,0,0,0,1,0,0,1
9,40,0.0,0.0,0.0,0.0,0.0,0.0,0,1,0,...,0,1,0,0,0,0,1,0,0,1

In [37]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [38]:
X = df.drop('Recurred', axis=1)
y = df['Recurred']

In [39]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [40]:
scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [41]:
pca = PCA(n_components=0.95)

X_train_pca = pca.fit_transform(X_train_scaled)
X_test_pca = pca.transform(X_test_scaled)

In [42]:
model = LogisticRegression(max_iter=1000)

model.fit(X_train_pca, y_train)

LogisticRegression(max_iter=1000)

In [43]:
y_pred = model.predict(X_test_pca)

In [44]:
accuracy = accuracy_score(y_test, y_pred)

print("Accuracy:", accuracy)

Accuracy: 0.935064935064935

In [45]:
print("Original features:", X.shape[1])
print("PCA features:", X_train_pca.shape[1])

Original features: 37
PCA features: 22

In [46]:
from sklearn.pipeline import Pipeline
from sklearn.model_selection import GridSearchCV

pipe = Pipeline([
('pca', PCA()),
('model', LogisticRegression(max_iter=1000))
])

param_grid = {
'pca__n_components': list(range(1, X_train_scaled.shape[1]+1))
}

grid = GridSearchCV(pipe, param_grid, cv=5)

grid.fit(X_train_scaled, y_train)

print("Best components:", grid.best_params_)
print("Best score:", grid.best_score_)

Best components: {'pca__n_components': 27}
Best score: 0.9313061872025383

In [53]:
df.to_csv("thyroid_final_dataset.csv", index=False)